cc_binary(
  name = "main",
  # @ mark in deps means it comes from WORKSPACE
  deps = ["@repo0//module0:cls0"],
  srcs = ["main.cpp",],
)

cc_binary(
  name = "main1",
  deps = ["@repo0//module0:cls0"],
  srcs = ["main1.cpp",],
)
